import "./globals.css";

import { Lato } from "next/font/google";
import { Providers } from "./providers";
import Header from "@/components/Header";

const lato = Lato({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={lato.className}
        style={{
          "--bg": "var(--black)",
          "--fg": "var(--white)",
          "--fg-bright": "var(--gold-400)",
          "--fg-muted": "var(--gray-500)",
          margin: 0,
          background: "var(--bg)",
          color: "var(--fg)",
        }}
      >
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
